# Generated by Django 5.2.1 on 2025-07-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='autor_github_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='autor_linkedin_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='autor_picture',
            field=models.ImageField(blank=True, null=True, upload_to='escola/static/escola/imagens/autores/'),
        ),
    ]
