services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.development
    environment:
      - DJANGO_SETTINGS_MODULE=configs.settings.development
      - ENV_NAME=development
#     depends_on:
#       - db

#   db:
#     image: postgres:15
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     env_file:
#       - .env.development
#     ports:
#       - "5434:5432" #VOCE PODE ALTERAR A PORTA 5432:5432
# volumes:
#   postgres_data: