# Generated by Django 5.2.1 on 2025-07-07 14:30

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutoriais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('descricao', models.TextField()),
                ('introducao', django_ckeditor_5.fields.CKEditor5Field(default='<h2>Introdução</h2><p>Nesta seção, apresente o tema do tutorial e seus objetivos principais.</p>', verbose_name='Introdução')),
                ('conceitos', django_ckeditor_5.fields.CKEditor5Field(default='<h2>Conceitos Básicos</h2><p>Explique os conceitos fundamentais necessários para entender o tutorial.</p>', verbose_name='Conceitos Básicos')),
                ('exemplos', django_ckeditor_5.fields.CKEditor5Field(default="<h2>Exemplos Práticos</h2><pre><code class='language-python'># Adicione exemplos de código aqui</code></pre>", verbose_name='Exemplos Práticos')),
                ('conclusao', django_ckeditor_5.fields.CKEditor5Field(default='<h2>Conclusão</h2><p>Resuma os principais pontos abordados e sugira próximos passos.</p>', verbose_name='Conclusão')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('autor', models.CharField(max_length=50)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='escola/static/escola/imagens/tutoriais/')),
                ('categoria', models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('BioPython', 'BioPython'), ('Data Science', 'Data Science'), ('Web Development', 'Web Development')], default='Python', max_length=50)),
                ('nivel', models.CharField(choices=[('Iniciante', 'Iniciante'), ('Intermediário', 'Intermediário'), ('Avançado', 'Avançado')], default='Iniciante', max_length=20)),
            ],
            options={
                'verbose_name': 'Tutorial',
                'verbose_name_plural': 'Tutoriais',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
