# Generated by Django 5.2.1 on 2025-06-13 14:56

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoriais', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutoriais',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Tutorial', 'verbose_name_plural': 'Tutoriais'},
        ),
        migrations.RemoveField(
            model_name='tutoriais',
            name='texto_principal',
        ),
        migrations.AddField(
            model_name='tutoriais',
            name='categoria',
            field=models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('BioPython', 'BioPython'), ('Data Science', 'Data Science'), ('Web Development', 'Web Development')], default='Python', max_length=50),
        ),
        migrations.AddField(
            model_name='tutoriais',
            name='conceitos',
            field=django_ckeditor_5.fields.CKEditor5Field(default='<h2>Conceitos Básicos</h2><p>Explique os conceitos fundamentais necessários para entender o tutorial.</p>', verbose_name='Conceitos Básicos'),
        ),
        migrations.AddField(
            model_name='tutoriais',
            name='conclusao',
            field=django_ckeditor_5.fields.CKEditor5Field(default='<h2>Conclusão</h2><p>Resuma os principais pontos abordados e sugira próximos passos.</p>', verbose_name='Conclusão'),
        ),
        migrations.AddField(
            model_name='tutoriais',
            name='exemplos',
            field=django_ckeditor_5.fields.CKEditor5Field(default="<h2>Exemplos Práticos</h2><pre><code class='language-python'># Adicione exemplos de código aqui</code></pre>", verbose_name='Exemplos Práticos'),
        ),
        migrations.AddField(
            model_name='tutoriais',
            name='introducao',
            field=django_ckeditor_5.fields.CKEditor5Field(default='<h2>Introdução</h2><p>Nesta seção, apresente o tema do tutorial e seus objetivos principais.</p>', verbose_name='Introdução'),
        ),
        migrations.AddField(
            model_name='tutoriais',
            name='nivel',
            field=models.CharField(choices=[('Iniciante', 'Iniciante'), ('Intermediário', 'Intermediário'), ('Avançado', 'Avançado')], default='Iniciante', max_length=20),
        ),
    ]
