# Generated by Django 5.2.1 on 2025-07-11 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoriais', '0002_tutoriais_autor_github_account_and_more'),
    ]

    operations = [
    ]
