# Generated by Django 5.2.1 on 2025-06-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoriais', '0002_alter_tutoriais_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoriais',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='escola/static/escola/imagens/tutoriais/'),
        ),
    ]
