# Generated by Django 5.2.1 on 2025-07-14 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoriais', '0003_auto_20250711_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutoriais',
            name='autor_github_account',
        ),
        migrations.RemoveField(
            model_name='tutoriais',
            name='autor_linkedin_account',
        ),
        migrations.RemoveField(
            model_name='tutoriais',
            name='autor_picture',
        ),
    ]
