# Generated by Django 5.2.1 on 2025-07-14 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoriais', '0004_remove_tutoriais_autor_github_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoriais',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoriais', to=settings.AUTH_USER_MODEL),
        ),
    ]
