# Generated by Django 5.2.1 on 2025-07-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoriais', '0005_alter_tutoriais_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoriais',
            name='exemplo1',
            field=models.TextField(blank=True, help_text='Código Python para o primeiro exemplo', null=True, verbose_name='Exemplo 1'),
        ),
        migrations.AddField(
            model_name='tutoriais',
            name='exemplo2',
            field=models.TextField(blank=True, help_text='Código Python para o segundo exemplo', null=True, verbose_name='Exemplo 2'),
        ),
        migrations.AddField(
            model_name='tutoriais',
            name='exemplo3',
            field=models.TextField(blank=True, help_text='Código Python para o terceiro exemplo', null=True, verbose_name='Exemplo 3'),
        ),
        migrations.AlterField(
            model_name='tutoriais',
            name='categoria',
            field=models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('Flask', 'Flask'), ('Data Engineering', 'Data Engineering'), ('Java Script', 'Java Script'), ('Go', 'Go'), ('Linux', 'Linux'), ('Machine Learning', 'Machine Learning'), ('BioPython', 'BioPython'), ('Data Science', 'Data Science'), ('Web Development', 'Web Development'), ('PostgreSQL', 'PostgreSQL'), ('MySQL', 'MySQL'), ('MongoDB', 'MongoDB'), ('Docker', 'Docker'), ('Kubernetes', 'Kubernetes'), ('Git', 'Git'), ('GitHub', 'GitHub'), ('CI/CD', 'CI/CD'), ('DevOps', 'DevOps'), ('Cloud Computing', 'Cloud Computing')], default='Python', max_length=50),
        ),
    ]
