# Generated by Django 5.2.1 on 2025-07-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoriais', '0006_tutoriais_exemplo1_tutoriais_exemplo2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoriais',
            name='categoria',
            field=models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('Flask', 'Flask'), ('Data Engineering', 'Data Engineering'), ('Java Script', 'Java Script'), ('Go', 'Go'), ('Linux', 'Linux'), ('Machine Learning', 'Machine Learning'), ('BioPython', 'BioPython'), ('Data Science', 'Data Science'), ('Web Development', 'Web Development'), ('PostgreSQL', 'PostgreSQL'), ('MySQL', 'MySQL'), ('MongoDB', 'MongoDB'), ('Docker', 'Docker'), ('Kubernetes', 'Kubernetes'), ('Git', 'Git'), ('GitHub', 'GitHub'), ('CI/CD', 'CI/CD'), ('DevOps', 'DevOps'), ('Cloud Computing', 'Cloud Computing'), ('Bash scripting', 'Bash scripting')], default='Python', max_length=50),
        ),
    ]
