# Generated by Django 5.2.1 on 2025-07-25 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoriais', '0007_alter_tutoriais_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutoriais',
            name='exemplos',
        ),
    ]
