# Generated by Django 5.2.1 on 2025-08-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('inscrito_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inscrição na Newsletter',
                'verbose_name_plural': 'Inscrições na Newsletter',
                'ordering': ['-inscrito_em'],
            },
        ),
    ]
