name: Test AWS Credentials

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  test-credentials:
    runs-on: ubuntu-latest
    
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Test AWS CLI
      run: |
        echo "Testing AWS credentials..."
        aws sts get-caller-identity
        echo "✅ AWS credentials are working!"
    
    - name: Test EC2 access
      run: |
        echo "Testing EC2 access..."
        aws ec2 describe-instances --instance-ids i-006ae61f3ad1d6aba
        echo "✅ EC2 access is working!"